[package]
name = "data-base-app-rs"
version = "0.1.0"
homepage = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
table_database_rs = { path = "../../../../../../rust_registry/table_database_rs" }
